# .golangci.yml
run:
  timeout: 3m
  tests: true
  allow-parallel-runners: true
  issues-exit-code: 1

output:
  formats:
    - format: colored-line-number

issues:
  # Show everything; don't collapse duplicates
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  enable:
    # --- core + widely available linters ---
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gci              # import grouping/format (configured below)
    - gosec
    - importas
    - inamedparam
    - intrange
    - ireturn
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

  # Helpful if you want to start strict and dial back later:
  disable-all: false
  fast: false

linters-settings:
  # ---- gci (import organizer) ----
  gci:
    # Local module path(s) — adjust to your real module path
    local-prefixes: voltpay_go
    # Custom section order (matches what you described)
    sections:
      - standard
      - default
      - prefix(voltpay_go)
      - blank
      - dot
      - alias
      - localmodule
    custom-order: true
    no-inline-comments: true
    no-prefix-comments: true
    no-lex-order: true

  # Keep lines readable but not too strict
  lll:
    line-length: 140
    tab-width: 1

  # Complexity budgets
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
    package-average: 0

  gocognit:
    min-complexity: 20

  funlen:
    lines: 120
    statements: 80

  # Magic numbers: warn on suspicious ones, ignore common cases
  mnd:
    ignored-numbers: [0,1,2,10,60,100,1024]
    ignored-functions: [strconv.Atoi, strconv.ParseInt, strconv.ParseUint, strconv.ParseFloat, time.Sleep]

  # misspell: en-GB or en-US; default en-US
  misspell:
    locale: US

  # error wrapping guidance
  wrapcheck:
    ignoreSigs:
      - errors.Join(error, ...)
      - errors.Wrap(...) # if you use pkg/errors; otherwise remove

  # depguard: prevent accidental imports (example only)
  depguard:
    rules:
      main:
        list-mode: allowlist
        files:
          - "**/*.go"
        allow:
          - "^context$"
          - "^errors$"
          - "^fmt$"
          - "^net/http$"
          - "^time$"
          - "^crypto/"
          - "^encoding/"
          - "^io$"
          - "^strings$"
          - "^github.com/go-chi/chi/v5"
          - "^github.com/GoogleCloudPlatform/functions-framework-go"
          - "^github.com/golang-jwt/jwt/v5"
          - "^github.com/lestrrat-go/jwx/v2/jwt"
          - "^golang.org/x/"
          - "^voltpay_go/"    # your local pkgs
        # Set to "denylist" and move approved packages to "deny" to invert policy.

  # nolint comments must have a reason
  nolintlint:
    require-explanation: true
    require-specific: true

  # revive: a reasonable baseline rule set
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: package-comments
      - name: range-val-in-closure
      - name: unreachable-code
      - name: unnecessary-stmt
      - name: unexported-return
      - name: error-naming
      - name: errorf
      - name: receiver-naming
      - name: time-naming

  # var name length (be pragmatic)
  varnamelen:
    min-name-length: 2
    max-name-length: 32
    check-receiver: false
    check-return: false
    check-parameter: false

  # gosec: tune noisy rules if needed
  gosec:
    excludes:
      - G115 # integer overflow false-positives on strconv Atoi

# Optional: fine-grained exclude examples (start empty)
# exclude-rules:
#   - linters: [lll]
#     source: "^//go:generate"
