name: voltpay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_app_check: ^0.4.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.0.2
  go_router: ^16.2.1
  flutter_riverpod: ^2.6.1
  smooth_page_indicator: ^1.2.1
  with_opacity: ^0.0.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  freezed: ^3.1.0
  dart_pre_commit: ^5.4.8
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
