name: voltpay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.1
  firebase_app_check: ^0.4.0
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  encrypt: ^5.0.1
  crypto: ^3.0.3
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.0.2
  go_router: ^16.2.1
  flutter_riverpod: ^3.0.3
  smooth_page_indicator: ^1.2.1
  with_opacity: ^0.0.2
  flutter_launcher_icons: ^0.14.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.2
  riverpod: ^3.0.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.0
  dargon2_flutter: ^3.3.0
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.2
  json_serializable: ^6.9.5
  freezed: ^3.1.0
  dart_pre_commit: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - 'assets/images/voltpay_jar.png'
    - 'assets/images/voltpay_remit.png'
    - 'assets/images/voltpay_send.png'
    - 'assets/images/voltpay_graph.png'
    - 'assets/images/voltpay_lock.png'
    - 'assets/images/voltpay_world.png'
    - 'assets/images/voltpay_email_pending.png'
    - 'assets/images/google.png'
    - 'assets/images/facebook.png'
    - 'assets/images/apple.png'
    - 'assets/images/passkey.png'
    - 'assets/data/countries.json'
    - 'assets/data/currencies.json'

