// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-uuC_dhfnJ8Cd7ODenMsR_H4EduGS_g',
    appId: '1:1018663726434:web:38d36a31cee4f90721503b',
    messagingSenderId: '1018663726434',
    projectId: 'micro-harbor-469912-u6',
    authDomain: 'micro-harbor-469912-u6.firebaseapp.com',
    storageBucket: 'micro-harbor-469912-u6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2Y4X0O2c6mCccwzdNAb128cVhqKoQwU',
    appId: '1:1018663726434:android:773c03b20e2c51d121503b',
    messagingSenderId: '1018663726434',
    projectId: 'micro-harbor-469912-u6',
    storageBucket: 'micro-harbor-469912-u6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1I_anjiU4ebS9nNRI76aXAGHW6HLri3k',
    appId: '1:1018663726434:ios:d489e7b036bd2fdf21503b',
    messagingSenderId: '1018663726434',
    projectId: 'micro-harbor-469912-u6',
    storageBucket: 'micro-harbor-469912-u6.firebasestorage.app',
    androidClientId:
        '1018663726434-l2uc63ilinvrma2s3fk7rivit3rv18o9.apps.googleusercontent.com',
    iosBundleId: 'net.metalbrain.voltpay',
  );
}