name: Android Release

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Flutter flavor (optional)"
        required: false
        default: ""

jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/voltpay-release.keystore

      - name: Create key.properties
        run: |
          cat > android/key.properties <<'EOF'
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=android/app/voltpay-release.keystore
          EOF

      - name: Build Android appbundle
        run: |
          if [ -n "${{ github.event.inputs.flavor }}" ]; then
            flutter build appbundle --release --flavor ${{ github.event.inputs.flavor }}
          else
            flutter build appbundle --release
          fi

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/**/app-*-release.aab
